{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*?template charset=latin1?*}
{default enable_print=true()}

<link rel="Home" href={"/"|ezurl} title="{'%sitetitle'|i18n('design/standard/layout',,hash('%sitetitle',$site.title))|wash}" />
<link rel="Index" href={"/"|ezurl} />
<link rel="Top"  href={"/"|ezurl} title="{$site_title}" />
<link rel="Search" href={"content/advancedsearch"|ezurl} title="{'Search %sitetitle'|i18n('design/standard/layout',,hash('%sitetitle',$site.title))|wash}" />
<link rel="Copyright" href={"/ezinfo/copyright"|ezurl} />
<link rel="Author" href={"/ezinfo/about"|ezurl} />

<link rel="Shortcut icon" href={"icons/favicon/favicon.ico"|ezimage} type="image/x-icon" />
<link rel="icon" type="image/png" href={"icons/favicon/favicon-32x32.png"|ezimage} sizes="32x32">
<link rel="icon" type="image/png" href={"icons/favicon/favicon-16x16.png"|ezimage} sizes="16x16">
<link rel="apple-touch-icon" sizes="180x180" href={"icons/favicon/apple-touch-icon.png"|ezimage}>
<link rel="manifest" href={"icons/favicon/manifest.json"|ezimage}>
<link rel="mask-icon" href={"icons/favicon/safari-pinned-tab.svg"|ezimage} color="#7ac143">
<meta name="msapplication-config" content={"icons/favicon/browserconfig.xml"|ezimage}>

{if $enable_print}
{* Add print <link> tag in JS to be cache safe with query string (not included in cache-block key by default in pagelayout) *}
<script type="text/javascript">
(function() {ldelim}

    var head = document.getElementsByTagName('head')[0];
    var printNode = document.createElement('link');
    printNode.rel = 'Alternate';
    printNode.href = "{concat( 'layout/set/print/', $site.uri.original_uri )|ezurl( 'no' )}" + document.location.search;
    printNode.media = 'print';
    printNode.title = "{'Printable version'|i18n('design/ezwebin/link')}";
    head.appendChild(printNode);

{rdelim})();
</script>
{/if}

{/default}
